### ISSUE TITLE
Too many try-catch block

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#11]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/1cdb20f79c4039a9edcd7ea9c31906947a3d2431/Unit%202/Activity%206.1.1/src/Main.java#L72-L103

Demasiados try-catch. Ten en cuenta que muchas de las excepciones sueltan un error común, basta con procesar todo el bloque con un try, si no, el código se vuelve ineficiente y poco legible.

**Comment by PDMP-2122** [comment]
Fixed
