### ISSUE TITLE
forEach

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#12]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/1cdb20f79c4039a9edcd7ea9c31906947a3d2431/Unit%202/Activity%206.1.1/src/Main.java#L175-L182

En Java, para recorrer una lista, es mejor -y más elegante- usar un bucle forEach:

for ( Contact c : list ) {
// hacer lo que toque con el contacto c
...
}

**Comment by PDMP-2122** [comment]
fixed
