### ISSUE TITLE
Mixed projects

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#18]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/0f6f2e2d6cbfd04620f49773750e7de5da68d4bd/Unit%203/Activity4.1.1/src/main/java/com/pdmp2223/unit3/activity4_1_1/ConsultaBD1.java#L9-L54

Has mezclado todo en un proyecto, indícamelo de alguna manera en la carpeta (441 - 443, por ejemplo). De todas maneras, se podrían haber hecho aquí proyectos diferentes para cada ejercicio (o métodos diferentes).

**Comment by PDMP-2122** [comment]
Fixed. He cambiado el nombre de la carpeta. Los próximos los hare separados
