### ISSUE TITLE
Closing resources

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#19]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/0f6f2e2d6cbfd04620f49773750e7de5da68d4bd/Unit%203/Activity4.1.1/src/main/java/com/pdmp2223/unit3/activity4_1_1/ConsultaBD1.java#L60-L63

Mira el punto 5 sobre cómo cerrar recursos de manera eficiente

**Comment by PDMP-2122** [comment]
Gracias por el comentario, he estado mirando, pero no me aclaro. He puesto una duda en el foro por si hay algún alumno mas con esa misma duda.
