### ISSUE TITLE
MegaModular ;)

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#2]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/e011de2d53e8518464732ab6233c49d22c747b0e/Unit%202/Activity%204.4.1/src/Main.java#L19

Esto es demasiada modularidad, Pablo, si por cada línea hacemos una función...

**Comment by PDMP-2122** [comment]
Corregido, lo he hecho menos modular
