### ISSUE TITLE
for

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#20]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/32bd4e7497f8e0f69cc64a1fa2e3a7cd9f994799/Unit%203/Activity%206.1.2/src/main/java/org/PDMP2122/unit3_6_1_2/DBPreparedStatement.java#L99

¿Porqué haces esto con un for?

**Comment by PDMP-2122** [comment]
El código lo saque del que hice en la practica 5.4.1 que lo hice con un while. El problema reside en que en la practica 5.4.1 me ha generado un archivo a parte llamado producción que al parecer es un código decompilado y no me he dado cuenta. No se porque a veces me sale este archivo de producción. Lo acabo de corregir.
