### ISSUE TITLE
upper

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#22]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/32bd4e7497f8e0f69cc64a1fa2e3a7cd9f994799/Unit%203/Activity%207.4.1-7.4.2-7.4.3/7.4.3%20Script%20namebupattern.txt#L17

Mejor: `upper(ename) like upper(pattern)`

**Comment by PDMP-2122** [comment]
Gracias!
