### ISSUE TITLE
parameter

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#7]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/e011de2d53e8518464732ab6233c49d22c747b0e/Unit%202/Activity%206.1.1/src/Main.java#L177

¿Para qué pasas la lista de personas como parámetro si la tienes como miembro de la clase?

**Comment by PDMP-2122** [comment]
Corregido.
