### ISSUE TITLE
Two lists

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#8]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/e011de2d53e8518464732ab6233c49d22c747b0e/Unit%202/Activity%206.1.1/src/Main.java#L10-L11

¿Para qué necesitas dos listas de personas? Por cierto, los nombres (personList1, personList2) no son nada descriptivos, no hay manera de saber en qué se distingue una de otra.

**Comment by PDMP-2122** [comment]
Corregido, He dejado solo una lista.
