### ISSUE TITLE
Program flow

### ISSUE THREAD

**Issue by jrgs** [PDMP-2122/DATA_ACCESS_PDMP_2223#9]
https://github.com/PDMP-2122/DATA_ACCESS_PDMP_2223/blob/e011de2d53e8518464732ab6233c49d22c747b0e/Unit%202/Activity%206.1.1/src/Main.java#L43-L61

Como ya comentamos en la tutoría, el flujo de programa adecuado sería:

1.- Leer el fichero de objetos (si existe) y meter los objetos en la lista
2.- Trabajar con la lista
3.- Escribir la lista de objetos en fichero al terminar

**Comment by PDMP-2122** [comment]
Corregido. Gracias por los comentarios
